### ISSUE TITLE
laser guns are horrendously bad

### ISSUE THREAD

**Issue by 6SpadesLuke** [Vault-Overseers/nuclear-14#483]
# Description

Using any laser weapon just feels bad. It's not a matter of skill or lag, multiple people have had instances of this "hitscan" weapon being delayed and just acting like regular guns with big trails.

# Reproduction

1. Open game
2. Game doesn't open

# Expected behavior

1. Grab laser gun
2. Load laser gun (Ignore if already loaded)
3. Locate enemy and fire at enemy

# Additional context

Multiple people have had complaints about this, laser weapons genuinely feel useless sometimes.

**Comment by 6SpadesLuke** [comment]
and some entity hitboxes are just off, I see bullets phase through molerats and deathclaws a lot

**Comment by justzick** [comment]
Was this bug observed in the vanilla build of the game?

Simply increasing the hitscan won't help here, it will make it much easier for projectiles to hit. Need to rewrite collision for hitscan.

**Comment by 6SpadesLuke** [comment]
there's modified versions of ss14?

**Comment by 6SpadesLuke** [comment]
I was playing on the vanilla ss14 launcher and playing in nuclear 14

**Comment by justzick** [comment]
Every time you enter a server with a different build, the launcher loads new mechanics. By vanilla build, I mean the Space Wizards build. If this problem is observed among them, it should be changed upstream, but not in this fork.

About monster hitboxes. They are not disabled, they are just quite crooked. This is already planned to be changed by #471, I think.

**Comment by 6SpadesLuke** [comment]
I was playing on the n14 build then, and alright
